

services:
  frontend:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=`mongodb+srv://farmaciadb:qeE8Zm8DQYuOslKZ@clusterfarmacia.8vvwtum.mongodb.net/farmacia?retryWrites=true&w=majority&appName=ClusterFarmacia`
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
   mongo-data: